//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_customer_bill
    {
        public int id { get; set; }
        public string type { get; set; }
        public Nullable<int> id_customer { get; set; }
        public string tenKH { get; set; }
        public Nullable<double> tongtien { get; set; }
        public Nullable<double> giamgia { get; set; }
        public Nullable<double> thucnhan { get; set; }
        public string method { get; set; }
        public Nullable<int> ispay { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<int> id_nguoitao { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string updated_by { get; set; }
        public int deleted { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date_sale { get; set; }
        public Nullable<int> id_center { get; set; }
        public Nullable<int> billtype { get; set; }
        public string note { get; set; }
        public string tennguoixuat { get; set; }
        public string code { get; set; }
    }
}
