//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_customer_bill_detail
    {
        public int id { get; set; }
        public Nullable<int> id_bill { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_code_product { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> unit { get; set; }
        public string unit_name { get; set; }
        public string note { get; set; }
        public string type { get; set; }
        public Nullable<int> status { get; set; }
        public string product_name { get; set; }
        public string groupcodeproduct { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
    }
}
