//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_customer
    {
        public int id { get; set; }
        public Nullable<int> id_center { get; set; }
        public string code_center { get; set; }
        public string fullname { get; set; }
        public string id_card { get; set; }
        public string address { get; set; }
        public string mobile { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string created_by { get; set; }
        public Nullable<int> status { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> id_card_date { get; set; }
        public string id_card_place { get; set; }
    }
}
