//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_Nhap
    {
        public int id { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public int soluong { get; set; }
        public Nullable<int> nguoinhap { get; set; }
        public int id_product { get; set; }
        public Nullable<double> tongtien { get; set; }
        public Nullable<double> giatrungbinh { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public int id_center { get; set; }
        public Nullable<int> id_nguonnhap { get; set; }
        public string group_code_product { get; set; }
        public string mota { get; set; }
    }
}
