//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_code_product
    {
        public int id { get; set; }
        public string code { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> id_nhap { get; set; }
        public Nullable<int> id_center { get; set; }
        public Nullable<double> giatrungbinh { get; set; }
        public string group_code { get; set; }
        public Nullable<bool> isactive { get; set; }
        public string note_code { get; set; }
        public Nullable<System.DateTime> ngayxuat { get; set; }
        public string nguoixuat { get; set; }
        public string tenKH { get; set; }
        public Nullable<int> id_bill_dt { get; set; }
    }
}
