//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_nguonnhap
    {
        public int id { get; set; }
        public string tennguon { get; set; }
        public string diachi { get; set; }
        public string sdt { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<int> id_center { get; set; }
        public string code { get; set; }
        public string description { get; set; }
    }
}
