//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_log
    {
        public string id { get; set; }
        public Nullable<long> date { get; set; }
        public string account { get; set; }
        public string type { get; set; }
        public string ipAddress { get; set; }
        public string ipAddressName { get; set; }
        public string moduleId { get; set; }
        public string moduleName { get; set; }
        public Nullable<bool> result { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> creatorTime { get; set; }
        public Nullable<int> creatorUserId { get; set; }
    }
}
