//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_tonkho
    {
        public int id { get; set; }
        public int id_product { get; set; }
        public int soluong { get; set; }
        public bool isactive { get; set; }
        public int id_center { get; set; }
    }
}
