//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_price
    {
        public int id { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<double> gia_nhap { get; set; }
        public Nullable<double> gia_xuat { get; set; }
        public string type_price { get; set; }
        public Nullable<bool> isactive { get; set; }
        public Nullable<System.DateTime> datecreate { get; set; }
        public Nullable<System.DateTime> date_modifiel { get; set; }
    }
}
