//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS.Data.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_lienhe
    {
        public int id { get; set; }
        public string hoten { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string email { get; set; }
        public string tieude { get; set; }
        public string noidung { get; set; }
        public Nullable<int> trangthai { get; set; }
        public Nullable<int> id_rep { get; set; }
        public Nullable<System.DateTime> ngaytraloi { get; set; }
        public string nguoitraloi { get; set; }
        public Nullable<System.DateTime> ngaygui { get; set; }
    }
}
